### ISSUE TITLE
About reffernce papers

### ISSUE THREAD

**Issue by rlacjfjin** [AlkisPlas/MPRJ_RCPSP#1]
Hi,
Could you add some papers or materials documentation which you have refferenced?

Thanks,

**Comment by AlkisPlas** [comment]
Hello,

All formulation source files begin with a reference comment to the corresponding papers.
Let me know if you need anything other than that.

Thank you

**Comment by rlacjfjin** [comment]
I didn't notice before, sorry.
Thanks for your sharing.
